config/routes.rb
Clexane::Application.routes.draw do
  resources :clexane_histories

  root :to => "medicines#index"
  
  resources :medicine_histories

  resources :picklines

  resources :medicines

  get "admin/index"

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'login' => :new
    delete 'logout' => :destroy
    get 'test1' => :test1
  end

  resources :users
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create' , as: :signup # post 'login' => :create
  get '/isloggedin', to: 'users#is_logged_in'
  post '/isloggedin', to: 'users#is_logged_in'

  resources :password_resets

end

app/models/medicine.rb
class Medicine < ActiveRecord::Base

	belongs_to :user
	has_many :medicine_histories, dependent: :destroy

  attr_accessible :canceledNotificationDate, :daysOffset, :daysOffsetStartDate, :firstHour, 
  					:isSpecificDays, :name, :secondHour, :specificDays#, :user_id

   validates :name, :user_id, presence: true 
 #  validates :price, numericality: {greater_than_or_equal_to: 0.01} 
 #  validates :title, uniqueness: true
 #  validates :image_url, allow_blank: true, format: {
 #    with:    %r{\.(gif|jpg|png)$}i,
	# message: 'must be a URL for GIF, JPG or PNG image.' 
 #  }
end

app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController
    #before_filter :authorize
    
  # GET /medicines
  # GET /medicines.json
  def index
    #@medicines = Medicine.all
    # @medicines = Medicine.order(:name)
    @medicines = Medicine.where("user_id = ?", current_user.id)
    #print 'session[:user_id]: ' ,session[:user_id]
    result = { "opcode" => 100, "response" => 200, "medicines" =>  @medicines }
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: result }
    end
  end

  # GET /medicines/1
  # GET /medicines/1.json
  def show
    @medicine = Medicine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @medicine }
    end
  end

  # GET /medicines/new
  # GET /medicines/new.json
  def new
    @medicine = Medicine.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @medicine }
    end
  end

  # GET /medicines/1/edit
  def edit
    @medicine = Medicine.find(params[:id])
  end

  # POST /medicines
  # POST /medicines.json
  def create
    #params[:medicine][:user_id] = session[:user_id]
    print 'in medicines/create, session[:user_id]: ' ,session[:user_id]

    # debugger
    if (params[:medicine])
      @medicine = Medicine.new(params[:medicine])
    else
      # debugger
      @medicine = Medicine.new(:name => params[:name], :specificDays => params[:specificDays], 
                               :canceledNotificationDate => params[:canceledNotificationDate], 
                               :daysOffset => params[:daysOffset],
                                :isSpecificDays => params[:isSpecificDays], :secondHour => params[:secondHour],
                                :daysOffsetStartDate => params[:daysOffsetStartDate], :firstHour => params[:firstHour])
    end

    @medicine.user_id = current_user.id
    respond_to do |format|
      if @medicine.save
        result = { "opcode" => 101, "response" => 200, "medicine" => @medicine }
      
        format.html { redirect_to @medicine, notice: 'Medicine was successfully created.' }
        format.json { render json: result, status: :created, location: result }
        #format.json { render json: @medicine, status: :created, location: @medicine }
      else
        format.html { render action: "new" }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
    # @medicine = Medicine.new(params[:medicine])

    # @medicine.user_id = session[:user_id]

    # respond_to do |format|
    #   if @medicine.save
    #     format.html { redirect_to @medicine, notice: 'Medicine was successfully created.' }
    #     format.json { render json: @medicine, status: :created, location: @medicine }
    #   else
    #     format.html { render action: "new" }
    #     format.json { render json: @medicine.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PUT /medicines/1
  # PUT /medicines/1.json
  def update
    @medicine = Medicine.find(params[:id])
    debugger
    respond_to do |format|
      if (params[:medicine])
        medicine = params[:medicine]
      else
      # debugger
        medicine = {:name => params[:name], :specificDays => params[:specificDays], 
                               :canceledNotificationDate => params[:canceledNotificationDate], 
                               :daysOffset => params[:daysOffset],
                                :isSpecificDays => params[:isSpecificDays], :secondHour => params[:secondHour],
                                :daysOffsetStartDate => params[:daysOffsetStartDate], 
                                :firstHour => params[:firstHour]}
      end
      if @medicine.update_attributes(medicine)#params[:medicine])
        result = { "opcode" => 102, "response" => 200, "medicine" => @medicine }
        format.html { redirect_to @medicine, notice: 'Medicine was successfully updated.' }
        format.json { render json: result, status: :created, location: result }
        # format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicines/1
  # DELETE /medicines/1.json
  def destroy
    @medicine = Medicine.find(params[:id])
    if @medicine.user_id == current_user.id
      @medicine.destroy

      respond_to do |format|
        format.html { redirect_to medicines_url }
        result = { "opcode" => 105, "response" => 200 }
        format.json { render json: result }
      end
    else
      respond_to do |format|
        result = { "opcode" => 105, "response" => 401, "error_msg" =>  "Unauthorized" }
        format.html { redirect_to login_url, notice: "Logged out" }
        format.json { render json: result }
      end
    end

  end
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/views/medicines/_form.html.erb
<%= form_for(@medicine) do |f| %>
  <% if @medicine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medicine.errors.count, "error") %> prohibited this medicine from being saved:</h2>

      <ul>
      <% @medicine.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :daysOffset %><br />
    <%= f.number_field :daysOffset %>
  </div>
  <div class="field">
    <%= f.label :firstHour %><br />
    <%= f.time_select :firstHour %>
  </div>
  <div class="field">
    <%= f.label :secondHour %><br />
    <%= f.time_select :secondHour %>
  </div>
  <div class="field">
    <%= f.label :isSpecificDays %><br />
    <%= f.check_box :isSpecificDays %>
  </div>
  <div class="field">
    <%= f.label :specificDays %><br />
    <%= f.number_field :specificDays %>
  </div>
  <div class="field">
    <%= f.label :canceledNotificationDate %><br />
    <%= f.datetime_select :canceledNotificationDate %>
  </div>
  <div class="field">
    <%= f.label :daysOffsetStartDate %><br />
    <%= f.datetime_select :daysOffsetStartDate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/medicines/edit.html.erb
<h1>Editing medicine</h1>

<%= render 'form' %>

<%= link_to 'Show', @medicine %> |
<%= link_to 'Back', medicines_path %>

app/views/medicines/index.html.erb
<h1>Listing medicines</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Daysoffset</th>
    <th>Firsthour</th>
    <th>Secondhour</th>
    <th>Isspecificdays</th>
    <th>Specificdays</th>
    <th>Cancelednotificationdate</th>
    <th>Daysoffsetstartdate</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @medicines.each do |medicine| %>
  <tr>
    <td><%= medicine.name %></td>
    <td><%= medicine.daysOffset %></td>
    <td><%= medicine.firstHour %></td>
    <td><%= medicine.secondHour %></td>
    <td><%= medicine.isSpecificDays %></td>
    <td><%= medicine.specificDays %></td>
    <td><%= medicine.canceledNotificationDate %></td>
    <td><%= medicine.daysOffsetStartDate %></td>
    <td><%= link_to 'Show', medicine %></td>
    <td><%= link_to 'Edit', edit_medicine_path(medicine) %></td>
    <td><%= link_to 'Destroy', medicine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Medicine', new_medicine_path %>

app/views/medicines/new.html.erb
<h1>New medicine</h1>

<%= render 'form' %>

<%= link_to 'Back', medicines_path %>

app/views/medicines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @medicine.name %>
</p>

<p>
  <b>Daysoffset:</b>
  <%= @medicine.daysOffset %>
</p>

<p>
  <b>Firsthour:</b>
  <%= @medicine.firstHour %>
</p>

<p>
  <b>Secondhour:</b>
  <%= @medicine.secondHour %>
</p>

<p>
  <b>Isspecificdays:</b>
  <%= @medicine.isSpecificDays %>
</p>

<p>
  <b>Specificdays:</b>
  <%= @medicine.specificDays %>
</p>

<p>
  <b>Cancelednotificationdate:</b>
  <%= @medicine.canceledNotificationDate %>
</p>

<p>
  <b>Daysoffsetstartdate:</b>
  <%= @medicine.daysOffsetStartDate %>
</p>


<%= link_to 'Edit', edit_medicine_path(@medicine) %> |
<%= link_to 'Back', medicines_path %>