config/routes.rb
Clexane::Application.routes.draw do
  resources :clexane_histories

  root :to => "medicines#index"
  
  resources :medicine_histories

  resources :picklines

  resources :medicines

  get "admin/index"

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'login' => :new
    delete 'logout' => :destroy
    get 'test1' => :test1
  end

  resources :users
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create' , as: :signup # post 'login' => :create
  get '/isloggedin', to: 'users#is_logged_in'
  post '/isloggedin', to: 'users#is_logged_in'

  resources :password_resets

end

app/models/medicine_history.rb
class MedicineHistory < ActiveRecord::Base

	belongs_to :medicine
	
	scope :today, -> { where("DATE(actualHour) = ?", Date.today) }
	scope :specificMedicineToday, lambda{ |medicine_id| where(medicine_id: medicine_id) unless medicine_id.nil? }

  attr_accessible :actualHour, :isFirstHour, :medicine_id, :c_type
end

app/controllers/medicine_histories_controller.rb
class MedicineHistoriesController < ApplicationController
  # GET /medicine_histories
  # GET /medicine_histories.json
  def index
    
    # @medicine_histories = MedicineHistory.joins({:medicine, :user})
    history_type = params[:history_type]
    opcode = 300
    if history_type == '0'
      @medicine_histories = MedicineHistory.all
      puts 'MedicineHistory.all - 0'
    elsif history_type == '1'
      @medicine_histories = current_user.medicine_histories.today
      opcode = 310
      puts 'today - 1'
    elsif history_type == '2'
      @medicine_histories = current_user.medicine_histories.today.specificMedicineToday(params[:medicine_id])
      opcode = 320
      puts 'specificMedicineToday - 2'
    end

    puts  'history_type: ', history_type, ' @medicine_histories: ', @medicine_histories
    respond_to do |format|
      result = { "opcode" => opcode, "response" => 200, "medicine_histories" => @medicine_histories }
      format.html # index.html.erb
      format.json { render json: result }
    end
  end

  # GET /medicine_histories/1
  # GET /medicine_histories/1.json
  def show
    @medicine_history = MedicineHistory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @medicine_history }
    end
  end

  # GET /medicine_histories/new
  # GET /medicine_histories/new.json
  def new
    @medicine_history = MedicineHistory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @medicine_history }
    end
  end

  # GET /medicine_histories/1/edit
  def edit
    @medicine_history = MedicineHistory.find(params[:id])
  end

  # POST /medicine_histories
  # POST /medicine_histories.json
  def create
    #@medicine_history = MedicineHistory.new(params[:medicine_history])
    @medicine = Medicine.find_by_id_and_user_id(params[:medicine_id], current_user.id)
    if @medicine
      if (params[:medicine_history])
        medicine_history = params[:medicine_history]
      else
      # debugger :, :, :medicineID, :
        medicine_history = {:actualHour => params[:actualHour], :isFirstHour => params[:isFirstHour], 
                               :c_type => params[:c_type] }
      end
      @medicine_history = @medicine.medicine_histories.new(medicine_history)
      #@order = @customer.orders.create(order_date: Time.now)

      respond_to do |format|
        if @medicine_history.save
          result = { "opcode" => 301, "response" => 200, "  " => @medicine_history }
          format.html { redirect_to @medicine_history, notice: 'Medicine history was successfully created.' }
          format.json { render json: result, status: :created, location: @medicine_history }
        else
          format.html { render action: "new" }
          format.json { render json: @medicine_history.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        result = { "opcode" => 301, "response" => 401, "error_msg" =>  "Unauthorized" }
        format.html { render action: "new" }
        format.json { render json: result }
      end
    end
  end

  # PUT /medicine_histories/1
  # PUT /medicine_histories/1.json
  def update
    @medicine_history = MedicineHistory.find(params[:id])

    respond_to do |format|
      if @medicine_history.update_attributes(params[:medicine_history])
        format.html { redirect_to @medicine_history, notice: 'Medicine history was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @medicine_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicine_histories/1
  # DELETE /medicine_histories/1.json
  def destroy
    @medicine_history = MedicineHistory.find(params[:id])
    @medicine = Medicine.find(@medicine_history.medicine_id)
    if @medicine.user_id == current_user.id
      @medicine_history.destroy

      respond_to do |format|
        format.html { redirect_to medicine_histories_url }
        result = { "opcode" => 305, "response" => 200 }
        format.json { render json: result }
      end
    else
      respond_to do |format|
        result = { "opcode" => 305, "response" => 401, "error_msg" =>  "Unauthorized" }
        format.html { redirect_to login_url, notice: "Logged out" }
        format.json { render json: result }
      end
    end
  end
end

app/helpers/medicine_histories_helper.rb
module MedicineHistoriesHelper
end

app/views/medicine_histories/_form.html.erb
<%= form_for(@medicine_history) do |f| %>
  <% if @medicine_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medicine_history.errors.count, "error") %> prohibited this medicine_history from being saved:</h2>

      <ul>
      <% @medicine_history.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :actualHour %><br />
    <%= f.datetime_select :actualHour %>
  </div>
  <div class="field">
    <%= f.label :c_type %><br />
    <%= f.number_field :c_type %>
  </div>
  <div class="field">
    <%= f.label :isFirstHour %><br />
    <%= f.check_box :isFirstHour %>
  </div>
  <div class="field">
    <%= f.label :medicine_id %><br />
    <%= f.number_field :medicine_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/medicine_histories/edit.html.erb
<h1>Editing medicine_history</h1>

<%= render 'form' %>

<%= link_to 'Show', @medicine_history %> |
<%= link_to 'Back', medicine_histories_path %>

app/views/medicine_histories/index.html.erb
<h1>Listing medicine_histories</h1>

<table>
  <tr>
    <th>Actualhour</th>
    <th>Type</th>
    <th>Isfirsthour</th>
    <th>medicine_id</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @medicine_histories.each do |medicine_history| %>
  <tr>
    <td><%= medicine_history.actualHour %></td>
    <td><%= medicine_history.c_type %></td>
    <td><%= medicine_history.isFirstHour %></td>
    <td><%= medicine_history.medicine_id %></td>
    <td><%= link_to 'Show', medicine_history %></td>
    <td><%= link_to 'Edit', edit_medicine_history_path(medicine_history) %></td>
    <td><%= link_to 'Destroy', medicine_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Medicine history', new_medicine_history_path %>

app/views/medicine_histories/new.html.erb
<h1>New medicine_history</h1>

<%= render 'form' %>

<%= link_to 'Back', medicine_histories_path %>

app/views/medicine_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Actualhour:</b>
  <%= @medicine_history.actualHour %>
</p>

<p>
  <b>Type:</b>
  <%= @medicine_history.c_type %>
</p>

<p>
  <b>Isfirsthour:</b>
  <%= @medicine_history.isFirstHour %>
</p>

<p>
  <b>medicine_id:</b>
  <%= @medicine_history.medicine_id %>
</p>


<%= link_to 'Edit', edit_medicine_history_path(@medicine_history) %> |
<%= link_to 'Back', medicine_histories_path %>