config/routes.rb
Clexane::Application.routes.draw do
  resources :clexane_histories

  root :to => "medicines#index"
  
  resources :medicine_histories

  resources :picklines

  resources :medicines

  get "admin/index"

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'login' => :new
    delete 'logout' => :destroy
    get 'test1' => :test1
  end

  resources :users
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create' , as: :signup # post 'login' => :create
  get '/isloggedin', to: 'users#is_logged_in'
  post '/isloggedin', to: 'users#is_logged_in'

  resources :password_resets

end

app/models/pickline.rb
class Pickline < ActiveRecord::Base

	belongs_to :user
  attr_accessible :bandage_interval_days, :bandage_replacement_date, 
  :blue_last_wash_date, :blue_ventile_replacement_date, :parpar_replacement_date, 
  :red_last_wash_date, :red_ventile_replacement_date, :user_id
end

app/controllers/picklines_controller.rb
class PicklinesController < ApplicationController

  # GET /picklines
  # GET /picklines.json
  def index
    #@picklines = Pickline.all
    @picklines = Pickline.where("user_id = ?", session[:user_id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @picklines }
    end
  end

  # GET /picklines/1
  # GET /picklines/1.json
  def show
    @pickline = Pickline.find(params[:id])
    result = { "opcode" => 200, "response" => 200, "pickline" =>  @pickline }

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: result }
    end
  end

  # GET /picklines/new
  # GET /picklines/new.json
  def new
    @pickline = Pickline.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pickline }
    end
  end

  # GET /picklines/1/edit
  def edit
    @pickline = Pickline.find(params[:id])
  end

  # POST /picklines
  # POST /picklines.json
  def create
    @pickline = Pickline.new(params[:pickline])

    respond_to do |format|
      if @pickline.save
        format.html { redirect_to @pickline, notice: 'Pickline was successfully created.' }
        format.json { render json: @pickline, status: :created, location: @pickline }
      else
        format.html { render action: "new" }
        format.json { render json: @pickline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /picklines/1
  # PUT /picklines/1.json
  def update
    @pickline = Pickline.find_by_id_and_user_id(params[:id], current_user.id)
    if @pickline
      puts 'pickline update - after authorization check'

      if (params[:pickline])
          pickline = params[:pickline]
      else
      # debugger
        pickline = {:blue_last_wash_date => params[:blue_last_wash_date], :red_last_wash_date => params[:red_last_wash_date], 
                               :bandage_replacement_date => params[:bandage_replacement_date], 
                               :bandage_interval_days => params[:bandage_interval_days],
                                :blue_ventile_replacement_date => params[:blue_ventile_replacement_date],
                                :red_ventile_replacement_date => params[:red_ventile_replacement_date],
                                :parpar_replacement_date => params[:parpar_replacement_date] }
      end
      respond_to do |format|
        if @pickline.update_attributes(pickline)
          result = { "opcode" => 201, "response" => 200, "pickline" =>  @pickline }
          format.html { redirect_to @pickline, notice: 'Pickline was successfully updated.' }
          format.json { render json: result }
        else
          format.html { render action: "edit" }
          format.json { render json: @pickline.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        result = { "opcode" => 201, "response" => 401, "error_msg" =>  "Unauthorized" }
        format.html { render action: "edit" }
        format.json { render json: result }
      end
    end
  end

  # DELETE /picklines/1
  # DELETE /picklines/1.json
  def destroy
    @pickline = Pickline.find(params[:id])
    @pickline.destroy

    respond_to do |format|
      format.html { redirect_to picklines_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/picklines_helper.rb
module PicklinesHelper
end

app/views/picklines/_form.html.erb
<%= form_for(@pickline) do |f| %>
  <% if @pickline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pickline.errors.count, "error") %> prohibited this pickline from being saved:</h2>

      <ul>
      <% @pickline.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :red_last_wash_date %><br />
    <%= f.date_select :red_last_wash_date %>
  </div>
  <div class="field">
    <%= f.label :blue_last_wash_date %><br />
    <%= f.date_select :blue_last_wash_date %>
  </div>
  <div class="field">
    <%= f.label :bandage_replacement_date %><br />
    <%= f.date_select :bandage_replacement_date %>
  </div>
  <div class="field">
    <%= f.label :blue_ventile_replacement_date %><br />
    <%= f.date_select :blue_ventile_replacement_date %>
  </div>
  <div class="field">
    <%= f.label :red_ventile_replacement_date %><br />
    <%= f.date_select :red_ventile_replacement_date %>
  </div>
  <div class="field">
    <%= f.label :bandage_interval_days %><br />
    <%= f.number_field :bandage_interval_days %>
  </div>
  <div class="field">
    <%= f.label :parpar_replacement_date %><br />
    <%= f.date_select :parpar_replacement_date %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/picklines/edit.html.erb
<h1>Editing pickline</h1>

<%= render 'form' %>

<%= link_to 'Show', @pickline %> |
<%= link_to 'Back', picklines_path %>

app/views/picklines/index.html.erb
<h1>Listing picklines</h1>

<table>
  <tr>
    <th>Red last wash date</th>
    <th>Blue last wash date</th>
    <th>Bandage replacement date</th>
    <th>Blue ventile replacement date</th>
    <th>Red ventile replacement date</th>
    <th>Bandage interval days</th>
    <th>Parpar replacement date</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @picklines.each do |pickline| %>
  <tr>
    <td><%= pickline.red_last_wash_date %></td>
    <td><%= pickline.blue_last_wash_date %></td>
    <td><%= pickline.bandage_replacement_date %></td>
    <td><%= pickline.blue_ventile_replacement_date %></td>
    <td><%= pickline.red_ventile_replacement_date %></td>
    <td><%= pickline.bandage_interval_days %></td>
    <td><%= pickline.parpar_replacement_date %></td>
    <td><%= pickline.user_id %></td>
    <td><%= link_to 'Show', pickline %></td>
    <td><%= link_to 'Edit', edit_pickline_path(pickline) %></td>
    <td><%= link_to 'Destroy', pickline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pickline', new_pickline_path %>

app/views/picklines/new.html.erb
<h1>New pickline</h1>

<%= render 'form' %>

<%= link_to 'Back', picklines_path %>

app/views/picklines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Red last wash date:</b>
  <%= @pickline.red_last_wash_date %>
</p>

<p>
  <b>Blue last wash date:</b>
  <%= @pickline.blue_last_wash_date %>
</p>

<p>
  <b>Bandage replacement date:</b>
  <%= @pickline.bandage_replacement_date %>
</p>

<p>
  <b>Blue ventile replacement date:</b>
  <%= @pickline.blue_ventile_replacement_date %>
</p>

<p>
  <b>Red ventile replacement date:</b>
  <%= @pickline.red_ventile_replacement_date %>
</p>

<p>
  <b>Bandage interval days:</b>
  <%= @pickline.bandage_interval_days %>
</p>

<p>
  <b>Parpar replacement date:</b>
  <%= @pickline.parpar_replacement_date %>
</p>

<p>
  <b>User:</b>
  <%= @pickline.user_id %>
</p>


<%= link_to 'Edit', edit_pickline_path(@pickline) %> |
<%= link_to 'Back', picklines_path %>